

export const allProducts=[
  // Clothing
  {
    id: "1",
    name: "Organic Cotton T-Shirt - Sustainable Fashion",
    price: 699,
    originalPrice: 899,
    rating: 4.5,
    reviewCount: 1247,
    greenRating: 5,
    certifications: 3,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=300&h=300&fit=crop",
    category: "clothing",
    description: "100% GOTS-certified organic cotton t-shirt with fair trade production",
    inStock: true,
  },
  {
    id: "2",
    name: "Recycled Polyester Hoodie",
    price: Math.round(45.99 * 83),
    originalPrice: Math.round(59.99 * 83),
    rating: 4.3,
    reviewCount: 892,
    greenRating: 4,
    certifications: 2,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=300&h=300&fit=crop",
    category: "clothing",
    description: "Made from 100% recycled plastic bottles with carbon-neutral shipping",
    inStock: true,
  },
  {
    id: "3",
    name: "Hemp Blend Jeans",
    price: Math.round(78.99 * 83),
    rating: 4.6,
    reviewCount: 654,
    greenRating: 5,
    certifications: 4,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=300&h=300&fit=crop",
    category: "clothing",
    description: "Sustainable hemp-cotton blend denim with natural indigo dye",
    inStock: true,
  },
  {
    id: "4",
    name: "Bamboo Fiber Dress",
    price: Math.round(65.99 * 83),
    originalPrice: Math.round(85.99 * 83),
    rating: 4.4,
    reviewCount: 423,
    greenRating: 5,
    certifications: 3,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=300&h=300&fit=crop",
    category: "clothing",
    description: "Soft bamboo fiber dress with antibacterial properties",
    inStock: true,
  },

  // Electronics
  {
    id: "5",
    name: "Solar-Powered Bluetooth Speaker",
    price: Math.round(89.99 * 83),
    originalPrice: Math.round(119.99 * 83),
    rating: 4.7,
    reviewCount: 2341,
    greenRating: 5,
    certifications: 4,
    image: "https://img.freepik.com/free-photo/electronic-device-table_417767-143.jpg?semt=ais_hybrid&w=740",
    category: "electronics",
    description: "Waterproof solar speaker with 20-hour battery life",
    inStock: true,
  },
  {
    id: "6",
    name: "Bamboo Fiber Phone Case",
    price: Math.round(19.99 * 83),
    rating: 4.2,
    reviewCount: 856,
    greenRating: 4,
    certifications: 2,
    image: "https://img.tvcmall.com/dynamic/uploads/details/740x740_660178279A-1.webp",
    category: "electronics",
    description: "Biodegradable phone case made from bamboo fiber composite",
    inStock: true,
  },
  {
    id: "7",
    name: "Recycled Aluminum Laptop Stand",
    price: Math.round(55.99 * 83),
    rating: 4.5,
    reviewCount: 1234,
    greenRating: 4,
    certifications: 3,
    image: "https://5.imimg.com/data5/SELLER/Default/2023/11/361016514/VP/EX/MI/200324666/pocket-simple-aluminium-laptop-stand-10-500x500.jpg",
    category: "electronics",
    description: "Ergonomic laptop stand made from 100% recycled aluminum",
    inStock: true,
  },
  {
    id: "8",
    name: "Wind-Up Emergency Radio",
    price: Math.round(34.99 * 83),
    rating: 4.1,
    reviewCount: 567,
    greenRating: 5,
    certifications: 2,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTerUQ1DHlf4HjgQOzqOy4W85sSnNPdv8HeMg&s",
    category: "electronics",
    description: "Hand-crank emergency radio with solar charging capability",
    inStock: true,
  },

  // Footwear
  {
    id: "9",
    name: "Recycled Ocean Plastic Sneakers",
    price: Math.round(95.99 * 83),
    originalPrice: Math.round(120.99 * 83),
    rating: 4.6,
    reviewCount: 1876,
    greenRating: 5,
    certifications: 4,
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=300&h=300&fit=crop",
    category: "footwear",
    description: "Comfortable sneakers made from recycled ocean plastic waste",
    inStock: true,
  },
  {
    id: "10",
    name: "Cork Sole Sandals",
    price: Math.round(42.99 * 83),
    rating: 4.3,
    reviewCount: 743,
    greenRating: 4,
    certifications: 3,
    image: "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=300&h=300&fit=crop",
    category: "footwear",
    description: "Sustainable cork sole sandals with organic cotton straps",
    inStock: true,
  },
  {
    id: "11",
    name: "Vegan Leather Boots",
    price: Math.round(128.99 * 83),
    originalPrice: Math.round(159.99 * 83),
    rating: 4.4,
    reviewCount: 892,
    greenRating: 4,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7-tuQll_JeZrwKvy3jZdnEXux_Zl1rMVHnQ&s",
    category: "footwear",
    description: "Durable vegan leather boots made from pineapple leaf waste",
    inStock: true,
  },

  // Home & Garden
  {
    id: "12",
    name: "Bamboo Kitchen Utensil Set",
    price: Math.round(28.99 * 83),
    rating: 4.5,
    reviewCount: 1456,
    greenRating: 5,
    certifications: 2,
    image: "https://5.imimg.com/data5/SELLER/Default/2023/5/312370206/VV/VZ/JK/120923699/ladies-purse-500x500.jpeg",
    category: "home-garden",
    description: "Complete bamboo kitchen utensil set with natural antimicrobial properties",
    inStock: true,
  },
  {
    id: "13",
    name: "Solar Garden Lights Set",
    price: Math.round(39.99 * 83),
    originalPrice: Math.round(54.99 * 83),
    rating: 4.2,
    reviewCount: 987,
    greenRating: 5,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdii7MKu6IJKyksfPUDA1G1FG9ZT4DhTtyCA&s",
    category: "home-garden",
    description: "Weather-resistant solar LED garden lights with auto on/off",
    inStock: true,
  },
  {
    id: "14",
    name: "Compost Bin - Recycled Plastic",
    price: Math.round(67.99 * 83),
    rating: 4.7,
    reviewCount: 654,
    greenRating: 5,
    certifications: 4,
    image: "https://plaswood.eco/wp-content/uploads/2020/03/recycled-plastic-compost-bin.jpg",
    category: "home-garden",
    description: "Large capacity compost bin made from 100% recycled plastic",
    inStock: true,
  },

  // Food & Beverages
  {
    id: "15",
    name: "Recycled Ocean Plastic Water Bottle",
    price: Math.round(15.99 * 83),
    rating: 4.3,
    reviewCount: 1892,
    greenRating: 5,
    certifications: 2,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=300&h=300&fit=crop",
    category: "food-beverages",
    description: "BPA-free water bottle made from recycled ocean plastic",
    inStock: true,
  },
  {
    id: "16",
    name: "Organic Fair Trade Coffee",
    price: Math.round(18.99 * 83),
    rating: 4.8,
    reviewCount: 2134,
    greenRating: 5,
    certifications: 4,
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=300&h=300&fit=crop",
    category: "food-beverages",
    description: "Single-origin organic coffee with fair trade certification",
    inStock: true,
  },
  {
    id: "17",
    name: "Reusable Silicone Food Bags",
    price: Math.round(24.99 * 83),
    originalPrice: Math.round(32.99 * 83),
    rating: 4.4,
    reviewCount: 1567,
    greenRating: 4,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRhLKrpD801h3ZJljaiZHJaGillQYGrS2DTA&s",
    category: "food-beverages",
    description: "Set of 6 reusable silicone food storage bags",
    inStock: true,
  },

  // Personal Care
  {
    id: "18",
    name: "Bamboo Toothbrush Set",
    price: Math.round(12.99 * 83),
    rating: 4.4,
    reviewCount: 1543,
    greenRating: 5,
    certifications: 2,
    image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=300&h=300&fit=crop",
    category: "personal-care",
    description: "Pack of 4 biodegradable bamboo toothbrushes",
    inStock: true,
  },
  {
    id: "19",
    name: "Zero Waste Shampoo Bar",
    price: Math.round(16.99 * 83),
    rating: 4.6,
    reviewCount: 876,
    greenRating: 5,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJpGMTcdOuZRewsmRpQRv3vZNq-WDE2Tidug&s",
    category: "personal-care",
    description: "Plastic-free shampoo bar with organic ingredients",
    inStock: true,
  },
  {
    id: "20",
    name: "Organic Cotton Towel Set",
    price: Math.round(48.99 * 83),
    originalPrice: Math.round(65.99 * 83),
    rating: 4.5,
    reviewCount: 1234,
    greenRating: 4,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUscu8LLaqB0JiuuOT7EWJPNfJ-cmruq6yAg&s",
    category: "personal-care",
    description: "Soft organic cotton towel set with GOTS certification",
    inStock: true,
  },

  // Beauty & Skincare
  {
    id: "21",
    name: "Organic Face Serum",
    price: Math.round(34.99 * 83),
    rating: 4.7,
    reviewCount: 2341,
    greenRating: 5,
    certifications: 4,
    image: "https://m.media-amazon.com/images/I/51jEoS-cYwL.jpg",
    category: "beauty-skincare",
    description: "Natural face serum with organic ingredients and zero waste packaging",
    inStock: true,
  },
  {
    id: "22",
    name: "Bamboo Makeup Brushes Set",
    price: Math.round(28.99 * 83),
    originalPrice: Math.round(39.99 * 83),
    rating: 4.3,
    reviewCount: 987,
    greenRating: 4,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH963QZWzTqbX5Xd3wGngEfzy8FKuA4mvppw&s",
    category: "beauty-skincare",
    description: "Complete makeup brush set with sustainable bamboo handles",
    inStock: true,
  },
  {
    id: "23",
    name: "Reusable Cotton Rounds",
    price: Math.round(18.99 * 83),
    rating: 4.5,
    reviewCount: 1456,
    greenRating: 5,
    certifications: 2,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrXFeMjPI-41-Om0QBnr-KREFnThz6wc_6fQ&s",
    category: "beauty-skincare",
    description: "Washable cotton rounds to replace disposable makeup wipes",
    inStock: true,
  },

  // Sports & Fitness
  {
    id: "24",
    name: "Recycled Yoga Mat",
    price: Math.round(45.99 * 83),
    originalPrice: Math.round(59.99 * 83),
    rating: 4.6,
    reviewCount: 1876,
    greenRating: 5,
    certifications: 4,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR05X7qmYcBDuRJq__rQz_7E2-KVemaD9w0EA&s",
    category: "sports-fitness",
    description: "Non-toxic yoga mat made from recycled materials",
    inStock: true,
  },
  {
    id: "25",
    name: "Bamboo Water Bottle",
    price: Math.round(22.99 * 83),
    rating: 4.4,
    reviewCount: 1234,
    greenRating: 4,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMT7L_74dhtAnt_pcdRKC2jZHMTXtCja_35Q&s",
    category: "sports-fitness",
    description: "Insulated bamboo water bottle for active lifestyles",
    inStock: true,
  },
  {
    id: "26",
    name: "Organic Cotton Gym Bag",
    price: Math.round(38.99 * 83),
    rating: 4.2,
    reviewCount: 654,
    greenRating: 4,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtQTdOyvDC_W48gCngQGa8Jw2seBqjqEOOlg&s",
    category: "sports-fitness",
    description: "Spacious gym bag made from organic cotton canvas",
    inStock: true,
  },

  // Books & Education
  {
    id: "27",
    name: "Sustainable Living Guide",
    price: Math.round(24.99 * 83),
    rating: 4.8,
    reviewCount: 892,
    greenRating: 5,
    certifications: 2,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=300&fit=crop",
    category: "books-education",
    description: "Comprehensive guide to sustainable living practices",
    inStock: true,
  },
  {
    id: "28",
    name: "Bamboo Notebook Set",
    price: Math.round(15.99 * 83),
    rating: 4.3,
    reviewCount: 567,
    greenRating: 4,
    certifications: 2,
    image: "https://5.imimg.com/data5/SELLER/Default/2023/2/ZF/ZF/UO/22145308/promotional-bamboo-notebook-set-promotional-notebook-set-500x500.jpeg",
    category: "books-education",
    description: "Set of 3 notebooks made from sustainable bamboo paper",
    inStock: true,
  },
  {
    id: "29",
    name: "Recycled Pencil Set",
    price: Math.round(8.99 * 83),
    rating: 4.1,
    reviewCount: 423,
    greenRating: 5,
    certifications: 2,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoWMtCS-Wrq33gLgiAouoPN85ZiDpkVydhVg&s",
    category: "books-education",
    description: "Pack of 12 pencils made from recycled newspaper",
    inStock: true,
  },

  // Pet Care
  {
    id: "30",
    name: "Organic Pet Food",
    price: Math.round(32.99 * 83),
    rating: 4.6,
    reviewCount: 1456,
    greenRating: 5,
    certifications: 4,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8E5KEaifPt2QiU0sN61eM9OKxun01imn_6w&s",
    category: "pet-care",
    description: "Organic pet food with sustainable packaging",
    inStock: true,
  },
  {
    id: "31",
    name: "Bamboo Pet Bowl Set",
    price: Math.round(26.99 * 83),
    rating: 4.4,
    reviewCount: 876,
    greenRating: 4,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIC9jt9OHsQLQhwxy0pkUviXkYqUkQGOvWoQ&s",
    category: "pet-care",
    description: "Durable pet bowls made from bamboo fiber",
    inStock: true,
  },
  {
    id: "32",
    name: "Recycled Pet Toys",
    price: Math.round(18.99 * 83),
    originalPrice: Math.round(24.99 * 83),
    rating: 4.2,
    reviewCount: 654,
    greenRating: 4,
    certifications: 2,
    image: "https://m.media-amazon.com/images/I/81CG0BCxsLL.jpg",
    category: "pet-care",
    description: "Set of pet toys made from recycled materials",
    inStock: true,
  },

  // Baby & Kids
  {
    id: "33",
    name: "Organic Cotton Baby Onesie",
    price: Math.round(22.99 * 83),
    rating: 4.7,
    reviewCount: 1234,
    greenRating: 5,
    certifications: 4,
    image: "https://www.momshome.in/cdn/shop/files/MHONESIE3TO6P4.jpg?v=1748081997",
    category: "baby-kids",
    description: "Soft organic cotton onesie for babies",
    inStock: true,
  },
  {
    id: "34",
    name: "Bamboo Baby Wipes",
    price: Math.round(16.99 * 83),
    originalPrice: Math.round(21.99 * 83),
    rating: 4.5,
    reviewCount: 987,
    greenRating: 5,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi1x2fT_zveSYvAjNZQ7XRyOVm1gcmek6Adg&s",
    category: "baby-kids",
    description: "Gentle bamboo baby wipes with natural ingredients",
    inStock: true,
  },
  {
    id: "35",
    name: "Wooden Educational Toys",
    price: Math.round(34.99 * 83),
    rating: 4.6,
    reviewCount: 756,
    greenRating: 5,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM25OcHIuwjvb6_qjnNySqHchYcDeS8BHDxQ&s",
    category: "baby-kids",
    description: "Set of wooden educational toys for toddlers",
    inStock: true,
  },

  // Office & Stationery
  {
    id: "36",
    name: "Recycled Paper Notebook",
    price: Math.round(12.99 * 83),
    rating: 4.3,
    reviewCount: 654,
    greenRating: 4,
    certifications: 2,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhD24zn8NT3oFHkFPKUEZOJ5Ftar4LSusNuQ&s",
    category: "office-stationery",
    description: "High-quality notebook made from 100% recycled paper",
    inStock: true,
  },
  {
    id: "37",
    name: "Bamboo Desk Organizer",
    price: Math.round(28.99 * 83),
    rating: 4.4,
    reviewCount: 432,
    greenRating: 4,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSULEUiq0nYqYgPq8YF-jrqHAqEC8FZl_aAFQ&s",
    category: "office-stationery",
    description: "Elegant bamboo desk organizer for office supplies",
    inStock: true,
  },
  {
    id: "38",
    name: "Plant-Based Ink Pens",
    price: Math.round(9.99 * 83),
    rating: 4.2,
    reviewCount: 321,
    greenRating: 4,
    certifications: 2,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqgRStzQNgHGKANS2xPOalt6Gabiuteg1iQg&s",
    category: "office-stationery",
    description: "Pack of 5 pens with plant-based ink",
    inStock: true,
  },

  // Outdoor & Camping
  {
    id: "39",
    name: "Solar Camping Lantern",
    price: Math.round(45.99 * 83),
    originalPrice: Math.round(59.99 * 83),
    rating: 4.6,
    reviewCount: 876,
    greenRating: 5,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbCoDGpBCkZS2btBuX4AZvjAMRrxWBo9oA3w&s",
    category: "outdoor-camping",
    description: "Portable solar-powered camping lantern",
    inStock: true,
  },
  {
    id: "40",
    name: "Bamboo Camping Utensils",
    price: Math.round(24.99 * 83),
    rating: 4.4,
    reviewCount: 543,
    greenRating: 4,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEBrIZKqlXCLZJJgslJD7ggmqBGDGw0TQgDw&s",
    category: "outdoor-camping",
    description: "Lightweight bamboo camping utensil set",
    inStock: true,
  },
  {
    id: "41",
    name: "Recycled Sleeping Bag",
    price: Math.round(89.99 * 83),
    rating: 4.5,
    reviewCount: 234,
    greenRating: 4,
    certifications: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8bfBfGvLffwd1vWRmsAbFTJypkt1Qrf8CQA&s",
    category: "outdoor-camping",
    description: "Warm sleeping bag made from recycled materials",
    inStock: true,
  },
]

export const categories = [
  { id: "clothing", name: "Sustainable Fashion", icon: "👕" },
  { id: "electronics", name: "Green Electronics", icon: "📱" },
  { id: "footwear", name: "Eco Footwear", icon: "👟" },
  { id: "home-garden", name: "Home & Garden", icon: "🏠" },
  { id: "personal-care", name: "Personal Care", icon: "🧴" },
  { id: "beauty-skincare", name: "Beauty & Skincare", icon: "💄" },
  { id: "sports-fitness", name: "Sports & Fitness", icon: "🏃‍♀️" },
  { id: "books-education", name: "Books & Education", icon: "📚" },
  { id: "pet-care", name: "Pet Care", icon: "🐾" },
  { id: "baby-kids", name: "Baby & Kids", icon: "👶" },
  { id: "office-stationery", name: "Office & Stationery", icon: "📝" },
  { id: "outdoor-camping", name: "Outdoor & Camping", icon: "🏕️" },
]


export function getProductById(id) {
  return allProducts.find((product) => product.id === id)
}

export function getProductsByCategory(category) {
  if (category === "all") return allProducts
  return allProducts.filter((product) => product.category === category)
}

export function searchProducts(query) {
  const lowercasedQuery = query.toLowerCase()
  return allProducts.filter((product) => product.name.toLowerCase().includes(lowercasedQuery))
}
