const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');
const bcrypt = require('bcryptjs');

// Load env
dotenv.config({ path: path.join(__dirname, '..', '.env') });

const User = require('../models/User');
const Product = require('../models/Product');
const Quiz = require('../models/Quiz');
const MarketplaceListing = require('../models/MarketplaceListing');
const Order = require('../models/Order');
const connectDB = require('../config/db');

// ---------- 1. ECO PRODUCTS DATA ----------
const allProducts = [
  { name: "Organic Cotton T-Shirt - Sustainable Fashion", price: 699, originalPrice: 899, rating: 4.5, reviewCount: 1247, greenRating: 5, certifications: 3, image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=300&h=300&fit=crop", category: "clothing", description: "100% GOTS-certified organic cotton t-shirt with fair trade production", inStock: true, type: 'new' },
  { name: "Recycled Polyester Hoodie", price: Math.round(45.99 * 83), originalPrice: Math.round(59.99 * 83), rating: 4.3, reviewCount: 892, greenRating: 4, certifications: 2, image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=300&h=300&fit=crop", category: "clothing", description: "Made from 100% recycled plastic bottles with carbon-neutral shipping", inStock: true, type: 'new' },
  { name: "Hemp Blend Jeans", price: Math.round(78.99 * 83), rating: 4.6, reviewCount: 654, greenRating: 5, certifications: 4, image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=300&h=300&fit=crop", category: "clothing", description: "Sustainable hemp-cotton blend denim with natural indigo dye", inStock: true, type: 'new' },
  { name: "Bamboo Fiber Dress", price: Math.round(65.99 * 83), originalPrice: Math.round(85.99 * 83), rating: 4.4, reviewCount: 423, greenRating: 5, certifications: 3, image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=300&h=300&fit=crop", category: "clothing", description: "Soft bamboo fiber dress with antibacterial properties", inStock: true, type: 'new' },
  { name: "Solar-Powered Bluetooth Speaker", price: Math.round(89.99 * 83), originalPrice: Math.round(119.99 * 83), rating: 4.7, reviewCount: 2341, greenRating: 5, certifications: 4, image: "https://img.freepik.com/free-photo/electronic-device-table_417767-143.jpg?semt=ais_hybrid&w=740", category: "electronics", description: "Waterproof solar speaker with 20-hour battery life", inStock: true, type: 'new' },
  { name: "Bamboo Fiber Phone Case", price: Math.round(19.99 * 83), rating: 4.2, reviewCount: 856, greenRating: 4, certifications: 2, image: "https://img.tvcmall.com/dynamic/uploads/details/740x740_660178279A-1.webp", category: "electronics", description: "Biodegradable phone case made from bamboo fiber composite", inStock: true, type: 'new' },
  { name: "Recycled Aluminum Laptop Stand", price: Math.round(55.99 * 83), rating: 4.5, reviewCount: 1234, greenRating: 4, certifications: 3, image: "https://5.imimg.com/data5/SELLER/Default/2023/11/361016514/VP/EX/MI/200324666/pocket-simple-aluminium-laptop-stand-10-500x500.jpg", category: "electronics", description: "Ergonomic laptop stand made from 100% recycled aluminum", inStock: true, type: 'new' },
  { name: "Wind-Up Emergency Radio", price: Math.round(34.99 * 83), rating: 4.1, reviewCount: 567, greenRating: 5, certifications: 2, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTerUQ1DHlf4HjgQOzqOy4W85sSnNPdv8HeMg&s", category: "electronics", description: "Hand-crank emergency radio with solar charging capability", inStock: true, type: 'new' },
  { name: "Recycled Ocean Plastic Sneakers", price: Math.round(95.99 * 83), originalPrice: Math.round(120.99 * 83), rating: 4.6, reviewCount: 1876, greenRating: 5, certifications: 4, image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=300&h=300&fit=crop", category: "footwear", description: "Comfortable sneakers made from recycled ocean plastic waste", inStock: true, type: 'new' },
  { name: "Cork Sole Sandals", price: Math.round(42.99 * 83), rating: 4.3, reviewCount: 743, greenRating: 4, certifications: 3, image: "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=300&h=300&fit=crop", category: "footwear", description: "Sustainable cork sole sandals with organic cotton straps", inStock: true, type: 'new' },
  { name: "Vegan Leather Boots", price: Math.round(128.99 * 83), originalPrice: Math.round(159.99 * 83), rating: 4.4, reviewCount: 892, greenRating: 4, certifications: 3, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7-tuQll_JeZrwKvy3jZdnEXux_Zl1rMVHnQ&s", category: "footwear", description: "Durable vegan leather boots made from pineapple leaf waste", inStock: true, type: 'new' },
  { name: "Bamboo Kitchen Utensil Set", price: Math.round(28.99 * 83), rating: 4.5, reviewCount: 1456, greenRating: 5, certifications: 2, image: "https://5.imimg.com/data5/SELLER/Default/2023/5/312370206/VV/VZ/JK/120923699/ladies-purse-500x500.jpeg", category: "home-garden", description: "Complete bamboo kitchen utensil set with natural antimicrobial properties", inStock: true, type: 'new' },
  { name: "Solar Garden Lights Set", price: Math.round(39.99 * 83), originalPrice: Math.round(54.99 * 83), rating: 4.2, reviewCount: 987, greenRating: 5, certifications: 3, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdii7MKu6IJKyksfPUDA1G1FG9ZT4DhTtyCA&s", category: "home-garden", description: "Weather-resistant solar LED garden lights with auto on/off", inStock: true, type: 'new' },
  { name: "Compost Bin - Recycled Plastic", price: Math.round(67.99 * 83), rating: 4.7, reviewCount: 654, greenRating: 5, certifications: 4, image: "https://plaswood.eco/wp-content/uploads/2020/03/recycled-plastic-compost-bin.jpg", category: "home-garden", description: "Large capacity compost bin made from 100% recycled plastic", inStock: true, type: 'new' },
  { name: "Recycled Ocean Plastic Water Bottle", price: Math.round(15.99 * 83), rating: 4.3, reviewCount: 1892, greenRating: 5, certifications: 2, image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=300&h=300&fit=crop", category: "food-beverages", description: "BPA-free water bottle made from recycled ocean plastic", inStock: true, type: 'new' },
  { name: "Organic Fair Trade Coffee", price: Math.round(18.99 * 83), rating: 4.8, reviewCount: 2134, greenRating: 5, certifications: 4, image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=300&h=300&fit=crop", category: "food-beverages", description: "Single-origin organic coffee with fair trade certification", inStock: true, type: 'new' },
  { name: "Reusable Silicone Food Bags", price: Math.round(24.99 * 83), originalPrice: Math.round(32.99 * 83), rating: 4.4, reviewCount: 1567, greenRating: 4, certifications: 3, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRhLKrpD801h3ZJljaiZHJaGillQYGrS2DTA&s", category: "food-beverages", description: "Set of 6 reusable silicone food storage bags", inStock: true, type: 'new' },
  { name: "Bamboo Toothbrush Set", price: Math.round(12.99 * 83), rating: 4.4, reviewCount: 1543, greenRating: 5, certifications: 2, image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=300&h=300&fit=crop", category: "personal-care", description: "Pack of 4 biodegradable bamboo toothbrushes", inStock: true, type: 'new' },
  { name: "Zero Waste Shampoo Bar", price: Math.round(16.99 * 83), rating: 4.6, reviewCount: 876, greenRating: 5, certifications: 3, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJpGMTcdOuZRewsmRpQRv3vZNq-WDE2Tidug&s", category: "personal-care", description: "Plastic-free shampoo bar with organic ingredients", inStock: true, type: 'new' },
  { name: "Organic Cotton Towel Set", price: Math.round(48.99 * 83), originalPrice: Math.round(65.99 * 83), rating: 4.5, reviewCount: 1234, greenRating: 4, certifications: 3, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUscu8LLaqB0JiuuOT7EWJPNfJ-cmruq6yAg&s", category: "personal-care", description: "Soft organic cotton towel set with GOTS certification", inStock: true, type: 'new' },
  { name: "Organic Face Serum", price: Math.round(34.99 * 83), rating: 4.7, reviewCount: 2341, greenRating: 5, certifications: 4, image: "https://m.media-amazon.com/images/I/51jEoS-cYwL.jpg", category: "beauty-skincare", description: "Natural face serum with organic ingredients and zero waste packaging", inStock: true, type: 'new' },
  { name: "Bamboo Makeup Brushes Set", price: Math.round(28.99 * 83), originalPrice: Math.round(39.99 * 83), rating: 4.3, reviewCount: 987, greenRating: 4, certifications: 3, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH963QZWzTqbX5Xd3wGngEfzy8FKuA4mvppw&s", category: "beauty-skincare", description: "Complete makeup brush set with sustainable bamboo handles", inStock: true, type: 'new' },
  { name: "Reusable Cotton Rounds", price: Math.round(18.99 * 83), rating: 4.5, reviewCount: 1456, greenRating: 5, certifications: 2, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrXFeMjPI-41-Om0QBnr-KREFnThz6wc_6fQ&s", category: "beauty-skincare", description: "Washable cotton rounds to replace disposable makeup wipes", inStock: true, type: 'new' },
  { name: "Recycled Yoga Mat", price: Math.round(45.99 * 83), originalPrice: Math.round(59.99 * 83), rating: 4.6, reviewCount: 1876, greenRating: 5, certifications: 4, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR05X7qmYcBDuRJq__rQz_7E2-KVemaD9w0EA&s", category: "sports-fitness", description: "Non-toxic yoga mat made from recycled materials", inStock: true, type: 'new' },
  { name: "Bamboo Water Bottle", price: Math.round(22.99 * 83), rating: 4.4, reviewCount: 1234, greenRating: 4, certifications: 3, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMT7L_74dhtAnt_pcdRKC2jZHMTXtCja_35Q&s", category: "sports-fitness", description: "Insulated bamboo water bottle for active lifestyles", inStock: true, type: 'new' },
  { name: "Organic Cotton Gym Bag", price: Math.round(38.99 * 83), rating: 4.2, reviewCount: 654, greenRating: 4, certifications: 3, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtQTdOyvDC_W48gCngQGa8Jw2seBqjqEOOlg&s", category: "sports-fitness", description: "Spacious gym bag made from organic cotton canvas", inStock: true, type: 'new' },
  { name: "Sustainable Living Guide", price: Math.round(24.99 * 83), rating: 4.8, reviewCount: 892, greenRating: 5, certifications: 2, image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=300&fit=crop", category: "books-education", description: "Comprehensive guide to sustainable living practices", inStock: true, type: 'new' },
  { name: "Bamboo Notebook Set", price: Math.round(15.99 * 83), rating: 4.3, reviewCount: 567, greenRating: 4, certifications: 2, image: "https://5.imimg.com/data5/SELLER/Default/2023/2/ZF/ZF/UO/22145308/promotional-bamboo-notebook-set-promotional-notebook-set-500x500.jpeg", category: "books-education", description: "Set of 3 notebooks made from sustainable bamboo paper", inStock: true, type: 'new' },
  { name: "Recycled Pencil Set", price: Math.round(8.99 * 83), rating: 4.1, reviewCount: 423, greenRating: 5, certifications: 2, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoWMtCS-Wrq33gLgiAouoPN85ZiDpkVydhVg&s", category: "books-education", description: "Pack of 12 pencils made from recycled newspaper", inStock: true, type: 'new' },
  { name: "Organic Pet Food", price: Math.round(32.99 * 83), rating: 4.6, reviewCount: 1456, greenRating: 5, certifications: 4, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8E5KEaifPt2QiU0sN61eM9OKxun01imn_6w&s", category: "pet-care", description: "Organic pet food with sustainable packaging", inStock: true, type: 'new' },
  { name: "Bamboo Pet Bowl Set", price: Math.round(26.99 * 83), rating: 4.4, reviewCount: 876, greenRating: 4, certifications: 3, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIC9jt9OHsQLQhwxy0pkUviXkYqUkQGOvWoQ&s", category: "pet-care", description: "Durable pet bowls made from bamboo fiber", inStock: true, type: 'new' },
  { name: "Recycled Pet Toys", price: Math.round(18.99 * 83), originalPrice: Math.round(24.99 * 83), rating: 4.2, reviewCount: 654, greenRating: 4, certifications: 2, image: "https://m.media-amazon.com/images/I/81CG0BCxsLL.jpg", category: "pet-care", description: "Set of pet toys made from recycled materials", inStock: true, type: 'new' },
  { name: "Organic Cotton Baby Onesie", price: Math.round(22.99 * 83), rating: 4.7, reviewCount: 1234, greenRating: 5, certifications: 4, image: "https://www.momshome.in/cdn/shop/files/MHONESIE3TO6P4.jpg?v=1748081997", category: "baby-kids", description: "Soft organic cotton onesie for babies", inStock: true, type: 'new' },
  { name: "Bamboo Baby Wipes", price: Math.round(16.99 * 83), originalPrice: Math.round(21.99 * 83), rating: 4.5, reviewCount: 987, greenRating: 5, certifications: 3, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi1x2fT_zveSYvAjNZQ7XRyOVm1gcmek6Adg&s", category: "baby-kids", description: "Gentle bamboo baby wipes with natural ingredients", inStock: true, type: 'new' },
  { name: "Wooden Educational Toys", price: Math.round(34.99 * 83), rating: 4.6, reviewCount: 756, greenRating: 5, certifications: 3, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM25OcHIuwjvb6_qjnNySqHchYcDeS8BHDxQ&s", category: "baby-kids", description: "Set of wooden educational toys for toddlers", inStock: true, type: 'new' },
  { name: "Recycled Paper Notebooks", price: Math.round(14.99 * 83), rating: 4.3, reviewCount: 892, greenRating: 4, certifications: 2, image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=300&fit=crop", category: "office-stationery", description: "Set of 5 notebooks made from 100% recycled paper", inStock: true, type: 'new' },
  { name: "Bamboo Desk Organizer", price: Math.round(29.99 * 83), originalPrice: Math.round(39.99 * 83), rating: 4.5, reviewCount: 1234, greenRating: 5, certifications: 3, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH963QZWzTqbX5Xd3wGngEfzy8FKuA4mvppw&s", category: "office-stationery", description: "Multi-functional desk organizer made from sustainable bamboo", inStock: true, type: 'new' },
  { name: "Biodegradable Pens Set", price: Math.round(12.99 * 83), rating: 4.2, reviewCount: 567, greenRating: 5, certifications: 2, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoWMtCS-Wrq33gLgiAouoPN85ZiDpkVydhVg&s", category: "office-stationery", description: "Pack of 10 biodegradable pens made from cornstarch plastic", inStock: true, type: 'new' },
  { name: "Solar Powered Camping Lantern", price: Math.round(45.99 * 83), originalPrice: Math.round(59.99 * 83), rating: 4.7, reviewCount: 1876, greenRating: 5, certifications: 4, image: "https://img.freepik.com/free-photo/electronic-device-table_417767-143.jpg?semt=ais_hybrid&w=740", category: "outdoor-camping", description: "Inflatable solar lantern for camping and emergency use", inStock: true, type: 'new' },
  { name: "Recycled Material Tent", price: Math.round(189.99 * 83), rating: 4.4, reviewCount: 423, greenRating: 4, certifications: 3, image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=300&h=300&fit=crop", category: "outdoor-camping", description: "4-person camping tent made from recycled polyester", inStock: true, type: 'new' },
  { name: "Biodegradable Camp Soap", price: Math.round(9.99 * 83), rating: 4.6, reviewCount: 1234, greenRating: 5, certifications: 3, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJpGMTcdOuZRewsmRpQRv3vZNq-WDE2Tidug&s", category: "outdoor-camping", description: "All-purpose biodegradable soap safe for outdoor use", inStock: true, type: 'new' },
];

// ---------- 2. REFURBISHED PRODUCTS DATA ----------
const refurbishedProducts = [
  {
    legacyId: "ref-1",
    name: "MacBook Pro 13\" (2020) - Refurbished",
    title: "MacBook Pro 13\" (2020) - Refurbished",
    category: "laptops",
    type: "refurbished",
    price: Math.round(899.0 * 83),
    refurbishedPrice: Math.round(899.0 * 83),
    originalPrice: Math.round(1299.0 * 83),
    savings: Math.round(400.0 * 83),
    condition: "excellent",
    warranty: "1 Year",
    warrantyMonths: 12,
    location: "Mumbai, Maharashtra",
    views: 156,
    likes: 23,
    sellerName: "Aarav S.",
    sellerRating: 4.9,
    sellerSales: 89,
    refurbishedBy: "Apple Certified",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop"],
    description: "Fully refurbished MacBook Pro with 8GB RAM and 256GB SSD. Includes 1-year warranty.",
    detailedDescription: "Professionally refurbished MacBook Pro (2020) featuring Intel Core processor, Retina display with True Tone technology, Magic Keyboard, and Touch Bar. Completely sanitized, benchmark tested, battery certified healthy.",
    features: ["Battery replaced", "Keyboard cleaned", "OS updated", "All ports tested"],
    specifications: { Display: "13.3-inch Retina", RAM: "8GB", Storage: "256GB SSD", Processor: "Intel Core i5" },
    inStock: true,
  },
  {
    legacyId: "ref-2",
    name: "iPhone 12 Pro - 128GB - Refurbished",
    title: "iPhone 12 Pro - 128GB - Refurbished",
    category: "smartphones",
    type: "refurbished",
    price: Math.round(649.0 * 83),
    refurbishedPrice: Math.round(649.0 * 83),
    originalPrice: Math.round(999.0 * 83),
    savings: Math.round(350.0 * 83),
    condition: "very-good",
    warranty: "6 Months",
    warrantyMonths: 6,
    location: "Delhi, Delhi",
    views: 203,
    likes: 31,
    sellerName: "Priya R.",
    sellerRating: 4.8,
    sellerSales: 156,
    refurbishedBy: "Certified Technician",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=400&fit=crop"],
    description: "Refurbished iPhone 12 Pro in excellent condition. New battery and screen protector included.",
    features: ["New battery", "Screen protector", "Charger included", "30-day return"],
    specifications: { Display: "6.1-inch Super Retina XDR", Storage: "128GB", Camera: "Triple 12MP", "5G": "Yes" },
    inStock: true,
  },
  {
    legacyId: "ref-3",
    name: "Sony WH-1000XM4 Headphones - Refurbished",
    title: "Sony WH-1000XM4 Headphones - Refurbished",
    category: "audio",
    type: "refurbished",
    price: Math.round(199.0 * 83),
    refurbishedPrice: Math.round(199.0 * 83),
    originalPrice: Math.round(349.0 * 83),
    savings: Math.round(150.0 * 83),
    condition: "excellent",
    warranty: "3 Months",
    warrantyMonths: 3,
    location: "Bengaluru, Karnataka",
    views: 89,
    likes: 12,
    sellerName: "Rohan K.",
    sellerRating: 4.7,
    sellerSales: 67,
    refurbishedBy: "Sony Certified",
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop"],
    description: "Premium noise-canceling headphones, fully tested and cleaned. Like new condition.",
    features: ["Deep cleaned", "New ear pads", "Bluetooth tested", "Case included"],
    specifications: { "Battery Life": "30 Hours", Connectivity: "Bluetooth 5.0", "Noise Canceling": "Active" },
    inStock: true,
  },
  {
    legacyId: "ref-4",
    name: "iPad Air 4th Gen - 64GB - Refurbished",
    title: "iPad Air 4th Gen - 64GB - Refurbished",
    category: "tablets",
    type: "refurbished",
    price: Math.round(399.0 * 83),
    refurbishedPrice: Math.round(399.0 * 83),
    originalPrice: Math.round(599.0 * 83),
    savings: Math.round(200.0 * 83),
    condition: "good",
    warranty: "6 Months",
    warrantyMonths: 6,
    location: "Chennai, Tamil Nadu",
    views: 134,
    likes: 18,
    sellerName: "Ananya M.",
    sellerRating: 4.6,
    sellerSales: 45,
    refurbishedBy: "Apple Certified",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop"],
    description: "Refurbished iPad Air with minor cosmetic wear. Fully functional with new battery.",
    features: ["New battery", "Screen tested", "Charger included", "Minor cosmetic wear"],
    specifications: { Display: "10.9-inch Liquid Retina", Chip: "A14 Bionic", Storage: "64GB" },
    inStock: true,
  },
  {
    legacyId: "ref-5",
    name: "Dell XPS 15 - Refurbished Laptop",
    title: "Dell XPS 15 - Refurbished Laptop",
    category: "laptops",
    type: "refurbished",
    price: Math.round(999.0 * 83),
    refurbishedPrice: Math.round(999.0 * 83),
    originalPrice: Math.round(1499.0 * 83),
    savings: Math.round(500.0 * 83),
    condition: "very-good",
    warranty: "1 Year",
    warrantyMonths: 12,
    location: "Hyderabad, Telangana",
    views: 178,
    likes: 25,
    sellerName: "Vikram P.",
    sellerRating: 4.8,
    sellerSales: 112,
    refurbishedBy: "Dell Certified",
    brand: "Dell",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop"],
    description: "Powerful Dell XPS 15 with 16GB RAM and 512GB SSD. Professional refurbishment.",
    features: ["OS reinstalled", "Hardware tested", "New thermal paste", "90-day return"],
    specifications: { Processor: "Intel Core i7", RAM: "16GB", Storage: "512GB SSD", Display: "15.6-inch FHD+" },
    inStock: true,
  },
  {
    legacyId: "ref-6",
    name: "Samsung Galaxy S21 - 128GB - Refurbished",
    title: "Samsung Galaxy S21 - 128GB - Refurbished",
    category: "smartphones",
    type: "refurbished",
    price: Math.round(449.0 * 83),
    refurbishedPrice: Math.round(449.0 * 83),
    originalPrice: Math.round(799.0 * 83),
    savings: Math.round(350.0 * 83),
    condition: "good",
    warranty: "6 Months",
    warrantyMonths: 6,
    location: "Kolkata, West Bengal",
    views: 167,
    likes: 22,
    sellerName: "Meera J.",
    sellerRating: 4.7,
    sellerSales: 89,
    refurbishedBy: "Samsung Certified",
    brand: "Samsung",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop"],
    description: "Refurbished Samsung Galaxy S21 with new battery and screen protector.",
    features: ["New battery", "Screen protector", "Charger included", "Minor wear"],
    specifications: { Display: "6.2-inch AMOLED", Storage: "128GB", RAM: "8GB", "5G": "Yes" },
    inStock: true,
  },
  {
    legacyId: "refurb-1",
    name: "iPhone 13 Pro - Refurbished",
    title: "iPhone 13 Pro - Refurbished",
    category: "smartphones",
    type: "refurbished",
    price: Math.round(649.99 * 83),
    refurbishedPrice: Math.round(649.99 * 83),
    originalPrice: 79999,
    savings: Math.round(350.0 * 83),
    condition: "Excellent",
    warranty: "1 Year Apple Warranty",
    warrantyMonths: 12,
    location: "Mumbai, Maharashtra",
    views: 156,
    likes: 23,
    sellerName: "TechHub Electronics",
    sellerRating: 4.8,
    sellerSales: 1247,
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=400&fit=crop"],
    features: ["128GB Storage", "Face ID", "Triple Camera System", "5G Ready"],
    inStock: true,
  },
  {
    legacyId: "refurb-2",
    name: "MacBook Air M1 - Refurbished",
    title: "MacBook Air M1 - Refurbished",
    category: "laptops",
    type: "refurbished",
    price: Math.round(899.99 * 83),
    refurbishedPrice: Math.round(899.99 * 83),
    originalPrice: 79999,
    savings: Math.round(400.0 * 83),
    condition: "Very Good",
    warranty: "90 Day Warranty",
    warrantyMonths: 3,
    location: "Bengaluru, Karnataka",
    views: 892,
    likes: 45,
    sellerName: "Premium Refurbs",
    sellerRating: 4.9,
    sellerSales: 892,
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&h=400&fit=crop"],
    features: ["M1 Chip", "8GB RAM", "256GB SSD", "13.3-inch Display"],
    inStock: true,
  },
  {
    legacyId: "refurb-3",
    name: "Samsung Galaxy Watch 4 - Refurbished",
    title: "Samsung Galaxy Watch 4 - Refurbished",
    category: "smartwatches",
    type: "refurbished",
    price: Math.round(199.99 * 83),
    refurbishedPrice: Math.round(199.99 * 83),
    originalPrice: 24999,
    savings: Math.round(130.0 * 83),
    condition: "Good",
    warranty: "6 Month Warranty",
    warrantyMonths: 6,
    location: "Pune, Maharashtra",
    views: 345,
    likes: 19,
    sellerName: "Shubham Electronics",
    sellerRating: 4.6,
    sellerSales: 654,
    brand: "Samsung",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsbr-E2kd878W2LtcFZQGHQgpC5ofshn63ZA&s",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsbr-E2kd878W2LtcFZQGHQgpC5ofshn63ZA&s"],
    features: ["Health Monitoring", "GPS", "Water Resistant", "40mm"],
    inStock: true,
  },
  {
    legacyId: "refurb-7",
    name: "Google Pixel 7 - Refurbished",
    title: "Google Pixel 7 - Refurbished",
    category: "smartphones",
    type: "refurbished",
    price: Math.round(449.99 * 83),
    refurbishedPrice: Math.round(449.99 * 83),
    originalPrice: 59999,
    savings: Math.round(250.0 * 83),
    condition: "Good",
    warranty: "6 Month Warranty",
    warrantyMonths: 6,
    location: "Kolkata, West Bengal",
    views: 450,
    likes: 33,
    sellerName: "Mobile World",
    sellerRating: 4.5,
    sellerSales: 789,
    brand: "Google",
    image: "https://bsmedia.business-standard.com/_media/bs/img/article/2024-08/22/thumb/fitandfill/1200X900/1724305131-8675.jpg",
    images: ["https://bsmedia.business-standard.com/_media/bs/img/article/2024-08/22/thumb/fitandfill/1200X900/1724305131-8675.jpg"],
    features: ["Google Tensor", "50MP Camera", "Android 13", "5G Ready"],
    inStock: true,
  },
  {
    legacyId: "refurb-8",
    name: "Microsoft Surface Pro 8 - Refurbished",
    title: "Microsoft Surface Pro 8 - Refurbished",
    category: "tablets",
    type: "refurbished",
    price: Math.round(699.99 * 83),
    refurbishedPrice: Math.round(699.99 * 83),
    originalPrice: 89999,
    savings: Math.round(400.0 * 83),
    condition: "Excellent",
    warranty: "1 Year Microsoft Warranty",
    warrantyMonths: 12,
    location: "Bengaluru, Karnataka",
    views: 567,
    likes: 42,
    sellerName: "Surface Specialists",
    sellerRating: 4.9,
    sellerSales: 567,
    brand: "Microsoft",
    image: "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=400&h=400&fit=crop"],
    features: ["Intel i5", "8GB RAM", "128GB SSD", "13-inch PixelSense"],
    inStock: true,
  },
  {
    legacyId: "refurb-cam-1",
    name: "Canon EOS R6 Mirrorless Camera Body - Refurbished",
    title: "Canon EOS R6 Mirrorless Camera Body - Refurbished",
    category: "cameras",
    type: "refurbished",
    price: 119999,
    refurbishedPrice: 119999,
    originalPrice: 189999,
    savings: 70000,
    condition: "Excellent",
    warranty: "1 Year Canon Authorized Warranty",
    warrantyMonths: 12,
    location: "Mumbai, Maharashtra",
    views: 420,
    likes: 38,
    sellerName: "Camera Pro Refurb",
    sellerRating: 4.8,
    sellerSales: 312,
    brand: "Canon",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=400&fit=crop"],
    features: ["20.1MP Full-Frame CMOS", "4K 60p 10-Bit Video", "In-Body Image Stabilizer", "Dual Card Slots"],
    inStock: true,
  },
  {
    legacyId: "refurb-cam-2",
    name: "Sony Alpha A7 III Full-Frame Camera - Refurbished",
    title: "Sony Alpha A7 III Full-Frame Camera - Refurbished",
    category: "cameras",
    type: "refurbished",
    price: 94999,
    refurbishedPrice: 94999,
    originalPrice: 145999,
    savings: 51000,
    condition: "Very Good",
    warranty: "6 Months Seller Warranty",
    warrantyMonths: 6,
    location: "Bengaluru, Karnataka",
    views: 610,
    likes: 54,
    sellerName: "Optics Hub",
    sellerRating: 4.7,
    sellerSales: 489,
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?w=400&h=400&fit=crop"],
    features: ["24.2MP BSI Sensor", "Fast Hybrid AF with Eye-AF", "4K HDR Video", "Z-battery long life"],
    inStock: true,
  },
  {
    legacyId: "refurb-game-1",
    name: "Sony PlayStation 5 (PS5) Digital Edition - Refurbished",
    title: "Sony PlayStation 5 (PS5) Digital Edition - Refurbished",
    category: "gaming",
    type: "refurbished",
    price: 36999,
    refurbishedPrice: 36999,
    originalPrice: 44999,
    savings: 8000,
    condition: "Excellent",
    warranty: "1 Year Sony Certified Warranty",
    warrantyMonths: 12,
    location: "New Delhi, Delhi",
    views: 950,
    likes: 88,
    sellerName: "NextGen Gaming Refurbs",
    sellerRating: 4.9,
    sellerSales: 820,
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&h=400&fit=crop"],
    features: ["Ultra-High Speed 825GB SSD", "Ray Tracing Support", "DualSense Controller Included", "Tempest 3D AudioTech"],
    inStock: true,
  },
  {
    legacyId: "refurb-game-2",
    name: "Nintendo Switch OLED Model - Refurbished",
    title: "Nintendo Switch OLED Model - Refurbished",
    category: "gaming",
    type: "refurbished",
    price: 24999,
    refurbishedPrice: 24999,
    originalPrice: 34999,
    savings: 10000,
    condition: "Excellent",
    warranty: "6 Months Warranty",
    warrantyMonths: 6,
    location: "Hyderabad, Telangana",
    views: 730,
    likes: 62,
    sellerName: "Pixel Arcade",
    sellerRating: 4.8,
    sellerSales: 640,
    brand: "Nintendo",
    image: "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400&h=400&fit=crop"],
    features: ["7-inch Vibrant OLED Screen", "64GB Internal Storage", "Enhanced Audio", "Wide Adjustable Stand"],
    inStock: true,
  },
  {
    legacyId: "refurb-game-3",
    name: "Xbox Series X 1TB Console - Refurbished",
    title: "Xbox Series X 1TB Console - Refurbished",
    category: "gaming",
    type: "refurbished",
    price: 39999,
    refurbishedPrice: 39999,
    originalPrice: 54999,
    savings: 15000,
    condition: "Very Good",
    warranty: "1 Year Microsoft Certified Warranty",
    warrantyMonths: 12,
    location: "Bengaluru, Karnataka",
    views: 520,
    likes: 47,
    sellerName: "Console Haven",
    sellerRating: 4.7,
    sellerSales: 390,
    brand: "Microsoft",
    image: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=400&h=400&fit=crop"],
    features: ["12 Teraflops GPU Power", "True 4K Gaming up to 120 FPS", "1TB Custom NVMe SSD", "Quick Resume"],
    inStock: true,
  },
  {
    legacyId: "refurb-acc-1",
    name: "Apple Magic Keyboard & Magic Mouse 2 - Refurbished",
    title: "Apple Magic Keyboard & Magic Mouse 2 - Refurbished",
    category: "accessories",
    type: "refurbished",
    price: 7999,
    refurbishedPrice: 7999,
    originalPrice: 15900,
    savings: 7901,
    condition: "Excellent",
    warranty: "6 Months Warranty",
    warrantyMonths: 6,
    location: "Mumbai, Maharashtra",
    views: 310,
    likes: 29,
    sellerName: "iCare Refurbs",
    sellerRating: 4.8,
    sellerSales: 280,
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop"],
    features: ["Rechargeable via Lightning", "Ultra-Slim Profile", "Multi-Touch Surface Mouse", "Auto-pairing with Mac"],
    inStock: true,
  },
  {
    legacyId: "refurb-acc-2",
    name: "Anker 737 Power Bank (PowerCore 24K 140W) - Refurbished",
    title: "Anker 737 Power Bank (PowerCore 24K 140W) - Refurbished",
    category: "accessories",
    type: "refurbished",
    price: 8499,
    refurbishedPrice: 8499,
    originalPrice: 13999,
    savings: 5500,
    condition: "Excellent",
    warranty: "1 Year Anker Warranty",
    warrantyMonths: 12,
    location: "Pune, Maharashtra",
    views: 480,
    likes: 51,
    sellerName: "Anker Direct Certified",
    sellerRating: 4.9,
    sellerSales: 910,
    brand: "Anker",
    image: "https://images.unsplash.com/photo-1609592424367-17b545d9e5a8?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1609592424367-17b545d9e5a8?w=400&h=400&fit=crop"],
    features: ["140W Two-Way Fast Charging", "Smart Digital Display", "24,000mAh Huge Capacity", "GaNPrime Technology"],
    inStock: true,
  },
  {
    legacyId: "refurb-aud-2",
    name: "Apple AirPods Pro (2nd Gen) with MagSafe Case - Refurbished",
    title: "Apple AirPods Pro (2nd Gen) with MagSafe Case - Refurbished",
    category: "audio",
    type: "refurbished",
    price: 14999,
    refurbishedPrice: 14999,
    originalPrice: 24900,
    savings: 9901,
    condition: "Excellent",
    warranty: "1 Year Certified Warranty",
    warrantyMonths: 12,
    location: "Bengaluru, Karnataka",
    views: 890,
    likes: 95,
    sellerName: "Audio Elite",
    sellerRating: 4.9,
    sellerSales: 1100,
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=400&h=400&fit=crop"],
    features: ["Active Noise Cancellation 2x stronger", "Adaptive Transparency", "Personalized Spatial Audio", "MagSafe Charging Case (USB-C)"],
    inStock: true,
  },
  {
    legacyId: "refurb-aud-3",
    name: "Bose QuietComfort 45 Wireless Headphones - Refurbished",
    title: "Bose QuietComfort 45 Wireless Headphones - Refurbished",
    category: "audio",
    type: "refurbished",
    price: 18999,
    refurbishedPrice: 18999,
    originalPrice: 29900,
    savings: 10901,
    condition: "Excellent",
    warranty: "1 Year Bose Certified Warranty",
    warrantyMonths: 12,
    location: "Chennai, Tamil Nadu",
    views: 580,
    likes: 67,
    sellerName: "Acoustic Vault",
    sellerRating: 4.8,
    sellerSales: 430,
    brand: "Bose",
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&h=400&fit=crop"],
    features: ["World-class noise cancelling", "Quiet and Aware Modes", "High-fidelity audio with adjustable EQ", "Up to 24 hours battery life"],
    inStock: true,
  },
  {
    legacyId: "refurb-watch-2",
    name: "Apple Watch Series 8 GPS 45mm - Refurbished",
    title: "Apple Watch Series 8 GPS 45mm - Refurbished",
    category: "smartwatches",
    type: "refurbished",
    price: 24999,
    refurbishedPrice: 24999,
    originalPrice: 45900,
    savings: 20901,
    condition: "Excellent",
    warranty: "1 Year Certified Warranty",
    warrantyMonths: 12,
    location: "Kolkata, West Bengal",
    views: 650,
    likes: 58,
    sellerName: "iWatch Store",
    sellerRating: 4.8,
    sellerSales: 520,
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1510017803434-a899398421b3?w=400&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1510017803434-a899398421b3?w=400&h=400&fit=crop"],
    features: ["Always-On Retina display", "Crash Detection & Fall Detection", "ECG and Blood Oxygen app", "Water resistant 50m"],
    inStock: true,
  },
  {
    legacyId: "refurb-phone-5",
    name: "OnePlus 9 Pro 5G (256GB, Pine Green) - Refurbished",
    title: "OnePlus 9 Pro 5G (256GB, Pine Green) - Refurbished",
    category: "smartphones",
    type: "refurbished",
    price: 26999,
    refurbishedPrice: 26999,
    originalPrice: 64999,
    savings: 38000,
    condition: "Very Good",
    warranty: "6 Months Seller Warranty",
    warrantyMonths: 6,
    location: "Ahmedabad, Gujarat",
    views: 490,
    likes: 41,
    sellerName: "OnePlus Specialist",
    sellerRating: 4.7,
    sellerSales: 350,
    brand: "OnePlus",
    image: "https://oasis.opstatics.com/content/dam/oasis/page/2021/9-series/spec-image/9-pro/Morning%20mist-gallery.png",
    images: ["https://oasis.opstatics.com/content/dam/oasis/page/2021/9-series/spec-image/9-pro/Morning%20mist-gallery.png"],
    features: ["Hasselblad Camera for Mobile", "120Hz Fluid AMOLED with LTPO", "Warp Charge 65T & Wireless 50W", "Snapdragon 888 5G"],
    inStock: true,
  }
];

// ---------- 3. P2P MARKETPLACE LISTINGS DATA ----------
const marketplaceListings = [
  {
    legacyId: "p2p-1",
    title: "Vintage Denim Jacket - Size M",
    category: "clothing",
    price: 799,
    condition: "good",
    description: "Classic vintage denim jacket in great condition. Slight fading which adds to the vintage look.",
    detailedDescription: "This beautiful vintage denim jacket is a timeless piece that never goes out of style. Made from high-quality denim with authentic vintage wash and fading that gives it character. Classic button closure, chest pockets, and side pockets.",
    images: [
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=300&h=300&fit=crop",
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=300&h=300&fit=crop",
    ],
    hasReceipt: false,
    location: "Mumbai, Maharashtra",
    views: 47,
    likes: 8,
    sellerName: "Aarav S.",
    sellerRating: 4.8,
    sellerSales: 23,
    status: "active",
    specifications: { Size: "Medium", Brand: "Vintage", Material: "100% Cotton Denim" },
  },
  {
    legacyId: "p2p-2",
    title: "Harry Potter Complete Book Set",
    category: "books",
    price: 1445,
    condition: "like-new",
    description: "Complete Harry Potter series in excellent condition. All 7 books included, barely read.",
    images: [
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=300&fit=crop",
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=300&fit=crop",
    ],
    hasReceipt: true,
    location: "Delhi, Delhi",
    views: 89,
    likes: 15,
    sellerName: "Priya R.",
    sellerRating: 4.9,
    sellerSales: 41,
    status: "active",
  },
  {
    legacyId: "p2p-3",
    title: "Ceramic Plant Pots Set of 3",
    category: "home-decor",
    price: 425,
    condition: "good",
    description: "Beautiful ceramic plant pots, perfect for small plants. One has a tiny chip but still functional.",
    images: [
      "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=300&h=300&fit=crop",
      "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=300&h=300&fit=crop",
    ],
    hasReceipt: false,
    location: "Bengaluru, Karnataka",
    views: 34,
    likes: 6,
    sellerName: "Rohan K.",
    sellerRating: 4.6,
    sellerSales: 12,
    status: "active",
  },
  {
    legacyId: "p2p-4",
    title: "Nike Running Shoes - Size 9",
    category: "sports",
    price: 555,
    condition: "good",
    description: "Nike Air Max running shoes, lightly used. Great for jogging and casual wear.",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&h=300&fit=crop",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&h=300&fit=crop",
    ],
    hasReceipt: true,
    location: "Chennai, Tamil Nadu",
    views: 67,
    likes: 12,
    sellerName: "Ananya M.",
    sellerRating: 4.7,
    sellerSales: 18,
    status: "active",
  },
  {
    legacyId: "p2p-5",
    title: "Wooden Chess Set - Handcrafted",
    category: "toys",
    price: 640,
    condition: "like-new",
    description: "Beautiful handcrafted wooden chess set. All pieces included, barely used.",
    images: [
      "https://images.unsplash.com/photo-1528819622765-d6bcf132f793?w=300&h=300&fit=crop",
      "https://images.unsplash.com/photo-1528819622765-d6bcf132f793?w=300&h=300&fit=crop",
    ],
    hasReceipt: false,
    location: "Hyderabad, Telangana",
    views: 23,
    likes: 4,
    sellerName: "Vikram P.",
    sellerRating: 4.5,
    sellerSales: 8,
    status: "active",
  },
  {
    legacyId: "p2p-6",
    title: "Bluetooth Wireless Headphones",
    category: "electronics",
    price: 7500,
    condition: "good",
    description: "Sony wireless headphones in good working condition. Minor wear on headband padding.",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&h=300&fit=crop",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&h=300&fit=crop",
    ],
    hasReceipt: true,
    location: "Kolkata, West Bengal",
    views: 91,
    likes: 18,
    sellerName: "Meera J.",
    sellerRating: 4.8,
    sellerSales: 29,
    status: "active",
  },
  {
    legacyId: "p2p-7",
    title: "Men's Cotton Shorts - Navy Blue",
    category: "clothing",
    price: 499,
    condition: "good",
    description: "Comfortable cotton shorts, perfect for summer. Lightly used, no stains or tears.",
    images: [
      "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=300&h=300&fit=crop",
    ],
    hasReceipt: false,
    location: "Pune, Maharashtra",
    views: 22,
    likes: 3,
    sellerName: "Rishi T.",
    sellerRating: 4.6,
    sellerSales: 7,
    status: "active",
  },
  {
    legacyId: "p2p-8",
    title: "Graphic Print T-Shirt - Large",
    category: "clothing",
    price: 429,
    condition: "like-new",
    description: "Trendy graphic print t-shirt, barely worn. 100% cotton, soft and breathable.",
    images: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&h=300&fit=crop",
    ],
    hasReceipt: false,
    location: "Bengaluru, Karnataka",
    views: 18,
    likes: 2,
    sellerName: "Sneha M.",
    sellerRating: 4.7,
    sellerSales: 11,
    status: "active",
  },
  {
    legacyId: "p2p-9",
    title: "Slim Fit Blue Jeans - 32W 32L",
    category: "clothing",
    price: 699,
    condition: "good",
    description: "Classic slim fit blue jeans, gently used. No rips, all buttons and zippers intact.",
    images: [
      "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=300&h=300&fit=crop",
    ],
    hasReceipt: false,
    location: "Ahmedabad, Gujarat",
    views: 25,
    likes: 4,
    sellerName: "Karan P.",
    sellerRating: 4.5,
    sellerSales: 9,
    status: "active",
  },
  {
    legacyId: "p2p-10",
    title: "Formal White Shirt - Size 40",
    category: "clothing",
    price: 549,
    condition: "like-new",
    description: "Elegant formal white shirt, worn only once for an interview. No marks, crisp and clean.",
    images: [
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=300&h=300&fit=crop",
    ],
    hasReceipt: false,
    location: "Delhi, Delhi",
    views: 30,
    likes: 5,
    sellerName: "Amit S.",
    sellerRating: 4.9,
    sellerSales: 15,
    status: "active",
  },
  {
    legacyId: "p2p-11",
    title: "Woolen Sweater - Maroon, Medium",
    category: "clothing",
    price: 649,
    condition: "good",
    description: "Warm woolen sweater, maroon color, perfect for winter. No holes or pilling.",
    images: [
      "https://images.unsplash.com/photo-1503602642458-232111445657?w=300&h=300&fit=crop",
    ],
    hasReceipt: false,
    location: "Jaipur, Rajasthan",
    views: 28,
    likes: 6,
    sellerName: "Pooja K.",
    sellerRating: 4.7,
    sellerSales: 13,
    status: "active",
  },
  {
    legacyId: "p2p-book-2",
    title: "The Overstory: A Novel - Richard Powers (Hardcover)",
    category: "books",
    price: 450,
    condition: "like-new",
    description: "Pulitzer prize winning novel on trees and nature. Read once, spine pristine, no markings.",
    detailedDescription: "The Overstory by Richard Powers, winner of the Pulitzer Prize in Fiction. An impassioned work of natural activism and resistance that is also a stunning evocation of the natural world.",
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&h=300&fit=crop"],
    hasReceipt: true,
    location: "Bengaluru, Karnataka",
    views: 65,
    likes: 12,
    sellerName: "Arjun K.",
    sellerRating: 4.9,
    sellerSales: 18,
    status: "active",
  },
  {
    legacyId: "p2p-book-3",
    title: "Braiding Sweetgrass - Robin Wall Kimmerer (Paperback)",
    category: "books",
    price: 380,
    condition: "good",
    description: "Indigenous wisdom, scientific knowledge and the teachings of plants. Great condition.",
    detailedDescription: "As a botanist, Robin Wall Kimmerer has been trained to ask questions of nature with the tools of science. As a member of the Citizen Potawatomi Nation, she embraces the notion that plants and animals are our oldest teachers.",
    images: ["https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=300&fit=crop"],
    hasReceipt: false,
    location: "Pune, Maharashtra",
    views: 45,
    likes: 8,
    sellerName: "Sunita P.",
    sellerRating: 4.8,
    sellerSales: 11,
    status: "active",
  },
  {
    legacyId: "p2p-home-2",
    title: "Handcrafted Reclaimed Wood Wall Clock",
    category: "home-decor",
    price: 1250,
    condition: "good",
    description: "12-inch rustic wall clock handcrafted from reclaimed teak wood with silent quartz movement.",
    detailedDescription: "Made entirely from reclaimed teak timber salvaged from old heritage homes. Each clock has distinct natural grain patterns, finished with natural beeswax polish.",
    images: ["https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=300&h=300&fit=crop"],
    hasReceipt: true,
    location: "Jaipur, Rajasthan",
    views: 115,
    likes: 24,
    sellerName: "Heritage Craft",
    sellerRating: 4.9,
    sellerSales: 34,
    status: "active",
  },
  {
    legacyId: "p2p-elec-2",
    title: "Keychron K2 Wireless Mechanical Keyboard (Gateron Brown)",
    category: "electronics",
    price: 4999,
    condition: "like-new",
    description: "Compact 75% layout, RGB backlight, connects with up to 3 devices via Bluetooth 5.1. Barely used.",
    detailedDescription: "Keychron K2 wireless mechanical keyboard with gentle Gateron Brown tactile switches. Compatible with Mac and Windows. Comes in original box with all keycaps and USB-C cable.",
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&h=300&fit=crop"],
    hasReceipt: true,
    location: "Hyderabad, Telangana",
    views: 230,
    likes: 35,
    sellerName: "Vikram N.",
    sellerRating: 4.8,
    sellerSales: 22,
    status: "active",
  },
  {
    legacyId: "p2p-sport-2",
    title: "Eco-Friendly Natural Cork & Rubber Yoga Mat (6mm)",
    category: "sports",
    price: 1499,
    condition: "like-new",
    description: "100% natural organic cork top with anti-slip natural tree rubber bottom. Odor-free and non-toxic.",
    detailedDescription: "Premium organic cork yoga mat offering exceptional non-slip grip that increases with perspiration. Antimicrobial, self-cleaning surface. Includes organic cotton carry strap.",
    images: ["https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=300&h=300&fit=crop"],
    hasReceipt: false,
    location: "Kochi, Kerala",
    views: 92,
    likes: 19,
    sellerName: "Maya T.",
    sellerRating: 4.9,
    sellerSales: 14,
    status: "active",
  },
  {
    legacyId: "p2p-toy-2",
    title: "Handmade Organic Wooden Stacking Rainbow & Blocks Set",
    category: "toys",
    price: 899,
    condition: "good",
    description: "Montessori-inspired wooden rainbow stacker colored with natural vegetable non-toxic dyes.",
    detailedDescription: "12-piece wooden rainbow stacker carved from sustainably harvested beech wood. Finished with child-safe vegetable dyes and organic coconut oil. Smooth rounded edges.",
    images: ["https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=300&h=300&fit=crop"],
    hasReceipt: true,
    location: "Dehradun, Uttarakhand",
    views: 78,
    likes: 15,
    sellerName: "Pooja V.",
    sellerRating: 4.7,
    sellerSales: 9,
    status: "active",
  }
];

// ---------- 4. QUIZ DATA ----------
const quizData = [
  {
    title: "Sustainable Living Basics",
    category: "sustainability",
    difficulty: "easy",
    estimatedMinutes: 5,
    totalPoints: 50,
    description: "Test your fundamental knowledge of eco-friendly practices.",
    questions: [
      {
        question: "Which material takes the longest to decompose in a landfill?",
        options: ["Aluminum Can", "Plastic Bottle", "Glass Bottle", "Paper Bag"],
        correctAnswer: 2,
        explanation: "Glass bottles can take upwards of 1 million years to decompose.",
        points: 10,
      },
      {
        question: "What percentage of household waste is typically compostable?",
        options: ["10-15%", "25-30%", "45-50%", "70-80%"],
        correctAnswer: 1,
        explanation: "Around 28-30% of average household waste consists of food scraps and yard trimmings.",
        points: 10,
      },
      {
        question: "Which everyday habit saves the most water?",
        options: ["Turning off tap while brushing", "Taking 5-min shorter showers", "Fixing a leaky toilet", "Running full laundry loads"],
        correctAnswer: 2,
        explanation: "A leaky toilet can silently waste over 200 gallons of clean water per day.",
        points: 10,
      },
      {
        question: "What does GOTS certification stand for in textiles?",
        options: ["Green Organic Textile Standard", "Global Organic Textile Standard", "General Organic Trade Standard", "Global Optimal Texture Standard"],
        correctAnswer: 1,
        explanation: "GOTS is the worldwide leading textile processing standard for organic fibres.",
        points: 10,
      },
      {
        question: "Which light bulb uses the least energy while lasting the longest?",
        options: ["Incandescent", "Halogen", "CFL", "LED"],
        correctAnswer: 3,
        explanation: "LED bulbs consume up to 90% less energy and last up to 25 times longer.",
        points: 10,
      },
    ],
  },
  {
    title: "Eco-Friendly Electronics & Tech",
    category: "eco-products",
    difficulty: "medium",
    estimatedMinutes: 7,
    totalPoints: 60,
    description: "Learn how to choose sustainable electronics and reduce e-waste.",
    questions: [
      {
        question: "How much greenhouse gas emissions does buying a refurbished phone avoid compared to a new one?",
        options: ["About 20%", "About 45%", "About 70-80%", "Almost 100%"],
        correctAnswer: 2,
        explanation: "Manufacturing accounts for ~80% of a phone's lifetime carbon footprint.",
        points: 15,
      },
      {
        question: "What precious metal is recovered in significant amounts from recycled printed circuit boards?",
        options: ["Gold", "Titanium", "Platinum", "Lead"],
        correctAnswer: 0,
        explanation: "One ton of circuit boards can contain 40 to 800 times more gold than a ton of gold ore.",
        points: 15,
      },
      {
        question: "What is 'vampire power' or phantom load in consumer electronics?",
        options: ["Battery surges", "Power consumed while devices are switched off or standby", "Static electricity", "Overheating"],
        correctAnswer: 1,
        explanation: "Standby power accounts for 5-10% of residential electricity use.",
        points: 15,
      },
      {
        question: "Which certification identifies energy-efficient consumer electronics?",
        options: ["Energy Star", "Fair Trade", "USDA Organic", "FSC"],
        correctAnswer: 0,
        explanation: "Energy Star is the international standard for energy-efficient consumer products.",
        points: 15,
      },
    ],
  },
  {
    title: "Climate Change & Carbon Footprint",
    category: "climate-change",
    difficulty: "hard",
    estimatedMinutes: 8,
    totalPoints: 80,
    description: "Challenge your understanding of carbon cycles and global sustainability targets.",
    questions: [
      {
        question: "Which sector is globally the largest contributor to greenhouse gas emissions?",
        options: ["Transportation", "Electricity & Heat Production", "Agriculture", "Manufacturing"],
        correctAnswer: 1,
        explanation: "Electricity and heat production accounts for approximately 25-30% of global greenhouse emissions.",
        points: 20,
      },
      {
        question: "What is the global target warming limit agreed under the Paris Agreement?",
        options: ["0.5°C", "1.5°C", "2.5°C", "3.0°C"],
        correctAnswer: 1,
        explanation: "The Paris Agreement aims to limit global temperature rise to well below 2°C, preferably 1.5°C.",
        points: 20,
      },
      {
        question: "How much carbon dioxide does an average mature tree absorb per year?",
        options: ["~5 kg", "~22 kg (48 lbs)", "~100 kg", "~500 kg"],
        correctAnswer: 1,
        explanation: "A mature tree absorbs approximately 22 kg (48 pounds) of carbon dioxide annually.",
        points: 20,
      },
      {
        question: "Which diet choice has the lowest carbon and land footprint per calorie?",
        options: ["Beef-heavy diet", "Plant-rich whole food diet", "Poultry-based diet", "Dairy-focused vegetarian diet"],
        correctAnswer: 1,
        explanation: "Plant-based whole foods require far less land and fossil energy per calorie produced.",
        points: 20,
      },
    ],
  },
];

// ---------- SEED FUNCTION ----------
const seedData = async (shouldExit = true) => {
  try {
    if (shouldExit) {
      await connectDB();
    }
    console.log('\n🌱 Starting database seed with ALL catalog, refurbished, and marketplace data...\n');

    // Clear existing data
    await User.deleteMany({});
    await Product.deleteMany({});
    await Quiz.deleteMany({});
    await MarketplaceListing.deleteMany({});
    await Order.deleteMany({});
    console.log('  ✓ Cleared existing collections');

    // 1. Seed users
    const users = [
      {
        name: 'Satvik',
        email: 'customer@amazon-green.com',
        password: 'Customer123!',
        type: 'customer',
        greenPoints: 2450,
        city: 'Bengaluru',
      },
      {
        name: 'Green Seller Co.',
        email: 'seller@amazon-green.com',
        password: 'Seller123!',
        type: 'seller',
        greenPoints: 0,
        city: 'Mumbai',
      },
    ];

    const createdUsers = await User.create(users);
    const customerUser = createdUsers.find(u => u.type === 'customer');
    const sellerUser = createdUsers.find(u => u.type === 'seller');
    console.log(`  ✓ Seeded ${createdUsers.length} users (Customer & Seller)`);

    // 2. Seed Eco Products
    const productsWithSeller = allProducts.map(p => ({
      ...p,
      sellerId: sellerUser._id,
      type: 'new',
    }));

    // 3. Combine with Refurbished Products
    const allProductsToSeed = [
      ...productsWithSeller,
      ...refurbishedProducts.map(r => ({
        ...r,
        sellerId: sellerUser._id,
      })),
    ];

    const createdProducts = await Product.create(allProductsToSeed);
    console.log(`  ✓ Seeded ${createdProducts.length} total products (41 Eco + ${refurbishedProducts.length} Refurbished)`);

    // 4. Seed P2P Marketplace Listings
    const listingsToSeed = marketplaceListings.map(item => ({
      ...item,
      sellerId: customerUser._id,
    }));
    const createdListings = await MarketplaceListing.create(listingsToSeed);
    console.log(`  ✓ Seeded ${createdListings.length} P2P Marketplace listings`);

    // 5. Seed Quizzes
    const normalizedQuizzes = quizData.map(q => ({
      ...q,
      questions: q.questions.map(quest => ({
        ...quest,
        answer: quest.correctAnswer !== undefined ? quest.correctAnswer : quest.answer,
        correctAnswer: quest.correctAnswer !== undefined ? quest.correctAnswer : quest.answer,
      }))
    }));
    const createdQuizzes = await Quiz.create(normalizedQuizzes);
    console.log(`  ✓ Seeded ${createdQuizzes.length} Quizzes`);

    // 6. Seed Demo Orders for Customer
    const firstTwoProducts = createdProducts.slice(0, 2);
    const demoOrders = [
      {
        userId: customerUser._id,
        items: [
          {
            productId: firstTwoProducts[0]._id,
            name: firstTwoProducts[0].name,
            price: firstTwoProducts[0].price,
            quantity: 2,
            image: firstTwoProducts[0].image,
            greenRating: 5,
          }
        ],
        shippingAddress: {
          street: '123 Green Street, Indiranagar',
          city: 'Bengaluru',
          state: 'Karnataka',
          pincode: '560038',
        },
        totalAmount: (firstTwoProducts[0].price * 2) + 20 - 50,
        greenPointsUsed: 50,
        greenPointsEarned: 139,
        discount: 50,
        status: 'delivered',
        trackingNumber: 'AMZ-GRN-1234567890',
        createdAt: new Date('2024-01-15'),
      },
      {
        userId: customerUser._id,
        items: [
          {
            productId: firstTwoProducts[1]._id,
            name: firstTwoProducts[1].name,
            price: firstTwoProducts[1].price,
            quantity: 1,
            image: firstTwoProducts[1].image,
            greenRating: 4,
          }
        ],
        shippingAddress: {
          street: '123 Green Street, Indiranagar',
          city: 'Bengaluru',
          state: 'Karnataka',
          pincode: '560038',
        },
        totalAmount: firstTwoProducts[1].price,
        greenPointsUsed: 0,
        greenPointsEarned: 30,
        discount: 0,
        status: 'pending',
        trackingNumber: 'AMZ-GRN-1234567891',
        createdAt: new Date('2024-01-22'),
      }
    ];

    await Order.create(demoOrders);
    console.log(`  ✓ Seeded ${demoOrders.length} Demo Customer Orders`);

    console.log('\n✅ Database completely seeded into MongoDB!\n');
    if (shouldExit) {
      process.exit(0);
    }
  } catch (error) {
    console.error('\n❌ Seed error:', error);
    if (shouldExit) {
      process.exit(1);
    }
    throw error;
  }
};

if (require.main === module) {
  seedData(true);
}

module.exports = seedData;
